/**
 * Environment types enum
 * Provides type-safe environment values
 */
export enum Environment {
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
  TEST = 'test',
  STAGING = 'staging',
}

/**
 * Log levels enum
 * Provides type-safe log level values
 */
export enum LogLevel {
  ERROR = 'error',
  WARN = 'warn',
  INFO = 'info',
  DEBUG = 'debug',
  VERBOSE = 'verbose',
}

/**
 * Database types enum
 * Provides type-safe database type values
 */
export enum DatabaseType {
  POSTGRES = 'postgres',
  MYSQL = 'mysql',
  SQLITE = 'sqlite',
  MONGODB = 'mongodb',
}

/**
 * Cache types enum
 * Provides type-safe cache type values
 */
export enum CacheType {
  REDIS = 'redis',
  MEMORY = 'memory',
  NONE = 'none',
}

/**
 * Authentication strategies enum
 * Provides type-safe auth strategy values
 */
export enum AuthStrategy {
  JWT = 'jwt',
  SESSION = 'session',
  API_KEY = 'api-key',
  OAUTH = 'oauth',
}

/**
 * Rate limiting strategies enum
 * Provides type-safe rate limiting strategy values
 */
export enum RateLimitStrategy {
  FIXED_WINDOW = 'fixed-window',
  SLIDING_WINDOW = 'sliding-window',
  TOKEN_BUCKET = 'token-bucket',
}

/**
 * Environment variable keys enum
 * Provides type-safe environment variable access
 */
export enum EnvVar {
  // Application
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  HOST = 'HOST',
  APP_NAME = 'APP_NAME',
  APP_VERSION = 'APP_VERSION',
  APP_DESCRIPTION = 'APP_DESCRIPTION',
  LOG_LEVEL = 'LOG_LEVEL',
  ENABLE_SWAGGER = 'ENABLE_SWAGGER',
  ENABLE_METRICS = 'ENABLE_METRICS',
  ENABLE_CORS = 'ENABLE_CORS',
  CORS_ORIGIN = 'CORS_ORIGIN',
  GLOBAL_PREFIX = 'GLOBAL_PREFIX',
  TIMEOUT = 'TIMEOUT',
  MAX_PAYLOAD_SIZE = 'MAX_PAYLOAD_SIZE',

  // Database
  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  DATABASE_URL = 'DATABASE_URL',
  DB_SSL = 'DB_SSL',
  DB_MAX_CONNECTIONS = 'DB_MAX_CONNECTIONS',
  DB_CONNECTION_TIMEOUT = 'DB_CONNECTION_TIMEOUT',
  DB_ACQUIRE_TIMEOUT = 'DB_ACQUIRE_TIMEOUT',
  DB_TIMEOUT = 'DB_TIMEOUT',
  DB_POOL_SIZE = 'DB_POOL_SIZE',

  // Authentication
  AUTH_STRATEGY = 'AUTH_STRATEGY',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',
  SALT_ROUNDS = 'SALT_ROUNDS',
  SESSION_MAX_AGE = 'SESSION_MAX_AGE',
  SESSION_SECRET = 'SESSION_SECRET',
  API_KEY_HEADER = 'API_KEY_HEADER',

  // OAuth Providers
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',
  GITHUB_CALLBACK_URL = 'GITHUB_CALLBACK_URL',

  // Cache
  CACHE_TYPE = 'CACHE_TYPE',
  CACHE_TTL = 'CACHE_TTL',
  CACHE_MAX_ITEMS = 'CACHE_MAX_ITEMS',

  // Redis
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_DB = 'REDIS_DB',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_KEY_PREFIX = 'REDIS_KEY_PREFIX',
  REDIS_RETRY_DELAY = 'REDIS_RETRY_DELAY',
  REDIS_MAX_RETRIES = 'REDIS_MAX_RETRIES',
  REDIS_ENABLE_READY_CHECK = 'REDIS_ENABLE_READY_CHECK',
  REDIS_MAX_MEMORY_POLICY = 'REDIS_MAX_MEMORY_POLICY',
  REDIS_LAZY_CONNECT = 'REDIS_LAZY_CONNECT',
  REDIS_KEEP_ALIVE = 'REDIS_KEEP_ALIVE',
  REDIS_FAMILY = 'REDIS_FAMILY',
  REDIS_NO_DELAY = 'REDIS_NO_DELAY',
  REDIS_CONNECTION_NAME = 'REDIS_CONNECTION_NAME',
  REDIS_READ_ONLY = 'REDIS_READ_ONLY',
  REDIS_STRING_NUMBERS = 'REDIS_STRING_NUMBERS',
  REDIS_MAX_LOADING_TIMEOUT = 'REDIS_MAX_LOADING_TIMEOUT',
  REDIS_AUTO_RESUBSCRIBE = 'REDIS_AUTO_RESUBSCRIBE',
  REDIS_AUTO_RESEND_COMMANDS = 'REDIS_AUTO_RESEND_COMMANDS',

  // Memory Cache
  MEMORY_CACHE_MAX_SIZE = 'MEMORY_CACHE_MAX_SIZE',
  MEMORY_CACHE_TTL = 'MEMORY_CACHE_TTL',
  MEMORY_CACHE_UPDATE_AGE = 'MEMORY_CACHE_UPDATE_AGE',
  MEMORY_CACHE_ALLOW_STALE = 'MEMORY_CACHE_ALLOW_STALE',
  MEMORY_CACHE_NO_DISPOSE = 'MEMORY_CACHE_NO_DISPOSE',

  // Rate Limiting
  RATE_LIMIT_ENABLED = 'RATE_LIMIT_ENABLED',
  RATE_LIMIT_STRATEGY = 'RATE_LIMIT_STRATEGY',
  RATE_LIMIT_TTL = 'RATE_LIMIT_TTL',
  RATE_LIMIT_LIMIT = 'RATE_LIMIT_LIMIT',
  RATE_LIMIT_SKIP_SUCCESS = 'RATE_LIMIT_SKIP_SUCCESS',
  RATE_LIMIT_SKIP_FAILED = 'RATE_LIMIT_SKIP_FAILED',
  RATE_LIMIT_KEY_GENERATOR = 'RATE_LIMIT_KEY_GENERATOR',
  RATE_LIMIT_HANDLER = 'RATE_LIMIT_HANDLER',

  // AWS
  AWS_REGION = 'AWS_REGION',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',

  // AWS S3
  AWS_S3_BUCKET = 'AWS_S3_BUCKET',
  AWS_S3_REGION = 'AWS_S3_REGION',
  AWS_S3_FORCE_PATH_STYLE = 'AWS_S3_FORCE_PATH_STYLE',
  AWS_S3_SIGNATURE_VERSION = 'AWS_S3_SIGNATURE_VERSION',
  AWS_S3_MAX_FILE_SIZE = 'AWS_S3_MAX_FILE_SIZE',
  AWS_S3_ALLOWED_MIME_TYPES = 'AWS_S3_ALLOWED_MIME_TYPES',
  AWS_S3_ENDPOINT = 'AWS_S3_ENDPOINT',
  AWS_S3_PUBLIC_URL = 'AWS_S3_PUBLIC_URL',

  // AWS SES
  AWS_SES_REGION = 'AWS_SES_REGION',
  AWS_SES_FROM_EMAIL = 'AWS_SES_FROM_EMAIL',
  AWS_SES_MAX_SEND_RATE = 'AWS_SES_MAX_SEND_RATE',
  AWS_SES_REPLY_TO_EMAIL = 'AWS_SES_REPLY_TO_EMAIL',
  AWS_SES_CONFIGURATION_SET = 'AWS_SES_CONFIGURATION_SET',

  // AWS SNS
  AWS_SNS_REGION = 'AWS_SNS_REGION',
  AWS_SNS_TOPIC_ARN = 'AWS_SNS_TOPIC_ARN',
  AWS_SNS_PLATFORM_APPLICATION_ARN = 'AWS_SNS_PLATFORM_APPLICATION_ARN',

  // Email
  EMAIL_PROVIDER = 'EMAIL_PROVIDER',
  EMAIL_FROM = 'EMAIL_FROM',
  EMAIL_REPLY_TO = 'EMAIL_REPLY_TO',

  // SMTP
  SMTP_HOST = 'SMTP_HOST',
  SMTP_PORT = 'SMTP_PORT',
  SMTP_SECURE = 'SMTP_SECURE',
  SMTP_USERNAME = 'SMTP_USERNAME',
  SMTP_PASSWORD = 'SMTP_PASSWORD',
  SMTP_FROM_NAME = 'SMTP_FROM_NAME',

  // SendGrid
  SENDGRID_API_KEY = 'SENDGRID_API_KEY',
  SENDGRID_FROM_NAME = 'SENDGRID_FROM_NAME',

  // Mailgun
  MAILGUN_API_KEY = 'MAILGUN_API_KEY',
  MAILGUN_DOMAIN = 'MAILGUN_DOMAIN',
  MAILGUN_FROM_NAME = 'MAILGUN_FROM_NAME',

  // Exception Filter
  MAX_ERROR_DETAILS_SIZE = 'MAX_ERROR_DETAILS_SIZE',
  ERROR_LOG_THRESHOLD = 'ERROR_LOG_THRESHOLD',
}
